version: '3.1'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=RSWC01
      - ORACLE_PDB=RSWPDB01
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - oradata:/opt/oracle/oradata
      - orabkp:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/RSWPDB01 as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oradata:
  orabkp: